name: TypeScript Smoke Test
on:
    push:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x

            - name: Install NPM dependencies
              run: npm install && cd test/typescript && npm install

            - name: Compile TypeScript sources
              run: cd test/typescript && npm run compile
